type SeedExercise = {
  code: string;
  name: string;
  description: string;
  muscleGroup: string;
  secondaryMuscles: string[];
  equipment: string[];
  difficulty: string;
  movementType: string;
  instructions: string[];
  safetyNotes?: string;
};

export const exerciseLibrary: SeedExercise[] = [
  // ===== CHEST =====
  {
    code: "dumbbell-bench-press",
    name: "Dumbbell Bench Press",
    description: "A chest-focused pressing movement using dumbbells.",
    muscleGroup: "Chest",
    secondaryMuscles: ["Triceps", "Front Deltoids"],
    equipment: ["DUMBBELLS", "BENCH"],
    difficulty: "BEGINNER",
    movementType: "COMPOUND",
    instructions: [
      "Lie on a flat bench holding dumbbells above your chest.",
      "Lower them to chest level with controlled motion.",
      "Press back up until arms are fully extended.",
    ],
    safetyNotes: "Keep feet planted and lower back neutral.",
  },
  {
    code: "push-ups",
    name: "Push Ups",
    description: "A classic bodyweight chest and triceps exercise.",
    muscleGroup: "Chest",
    secondaryMuscles: ["Triceps", "Front Deltoids", "Core"],
    equipment: ["NONE"],
    difficulty: "BEGINNER",
    movementType: "BODYWEIGHT",
    instructions: [
      "Start in a plank position with hands under shoulders.",
      "Lower your body until chest nears the floor.",
      "Press back to the starting position.",
    ],
    safetyNotes: "Keep your body in a straight line from head to heels.",
  },
  {
    code: "incline-dumbbell-press",
    name: "Incline Dumbbell Press",
    description: "Targets the upper chest with an incline bench.",
    muscleGroup: "Chest",
    secondaryMuscles: ["Triceps", "Front Deltoids"],
    equipment: ["DUMBBELLS", "BENCH"],
    difficulty: "INTERMEDIATE",
    movementType: "COMPOUND",
    instructions: [
      "Set the bench to a 30-45 degree incline.",
      "Press dumbbells up from shoulder level.",
      "Lower slowly back toward your chest.",
    ],
  },
  {
    code: "dumbbell-fly",
    name: "Dumbbell Fly",
    description: "An isolation exercise for the chest.",
    muscleGroup: "Chest",
    secondaryMuscles: ["Front Deltoids"],
    equipment: ["DUMBBELLS", "BENCH"],
    difficulty: "INTERMEDIATE",
    movementType: "ISOLATION",
    instructions: [
      "Lie on a bench with dumbbells above your chest.",
      "Open your arms in an arc until you feel a chest stretch.",
      "Squeeze chest to bring the dumbbells back together.",
    ],
    safetyNotes: "Keep a slight bend in the elbows.",
  },
  // ===== BACK =====
  {
    code: "pull-ups",
    name: "Pull Ups",
    description: "An upper-body pulling movement using your own bodyweight.",
    muscleGroup: "Back",
    secondaryMuscles: ["Biceps", "Rear Deltoids", "Core"],
    equipment: ["NONE"],
    difficulty: "INTERMEDIATE",
    movementType: "COMPOUND",
    instructions: [
      "Hang from a bar with hands slightly wider than shoulders.",
      "Pull your chest toward the bar.",
      "Lower with control back to a full hang.",
    ],
  },
  {
    code: "dumbbell-rows",
    name: "Dumbbell Row",
    description: "A single-arm row that builds the mid back.",
    muscleGroup: "Back",
    secondaryMuscles: ["Biceps", "Lats", "Rear Deltoids"],
    equipment: ["DUMBBELLS", "BENCH"],
    difficulty: "BEGINNER",
    movementType: "COMPOUND",
    instructions: [
      "Place one knee and hand on a bench, back flat.",
      "Pull the dumbbell toward your hip.",
      "Lower it with control.",
    ],
  },
  {
    code: "bent-over-dumbbell-row",
    name: "Bent Over Dumbbell Row",
    description: "A bilateral row for the back.",
    muscleGroup: "Back",
    secondaryMuscles: ["Biceps", "Rear Deltoids"],
    equipment: ["DUMBBELLS"],
    difficulty: "INTERMEDIATE",
    movementType: "COMPOUND",
    instructions: [
      "Hinge at the hips with a flat back.",
      "Row both dumbbells toward your lower rib cage.",
      "Lower with control.",
    ],
    safetyNotes: "Keep the spine neutral to avoid strain.",
  },
  {
    code: "superman",
    name: "Superman Hold",
    description: "Strengthens the lower back and spinal erectors.",
    muscleGroup: "Back",
    secondaryMuscles: ["Glutes", "Core"],
    equipment: ["NONE"],
    difficulty: "BEGINNER",
    movementType: "BODYWEIGHT",
    instructions: [
      "Lie face down with arms extended forward.",
      "Lift arms and legs off the floor together.",
      "Hold, then lower with control.",
    ],
  },
  {
    code: "band-lat-pulldown",
    name: "Resistance Band Lat Pulldown",
    description: "A band-based lat pulldown for home workouts.",
    muscleGroup: "Back",
    secondaryMuscles: ["Biceps", "Rear Deltoids"],
    equipment: ["RESISTANCE_BANDS"],
    difficulty: "BEGINNER",
    movementType: "COMPOUND",
    instructions: [
      "Anchor the band overhead and kneel.",
      "Pull the band down to your shoulders.",
      "Return slowly to the start.",
    ],
  },
  // ===== SHOULDERS =====
  {
    code: "dumbbell-shoulder-press",
    name: "Dumbbell Shoulder Press",
    description: "Overhead pressing for the deltoids.",
    muscleGroup: "Shoulders",
    secondaryMuscles: ["Triceps", "Upper Traps"],
    equipment: ["DUMBBELLS"],
    difficulty: "BEGINNER",
    movementType: "COMPOUND",
    instructions: [
      "Hold dumbbells at shoulder height.",
      "Press overhead until arms are extended.",
      "Lower back to shoulder height.",
    ],
  },
  {
    code: "lateral-raises",
    name: "Lateral Raise",
    description: "Isolation exercise for the side deltoids.",
    muscleGroup: "Shoulders",
    secondaryMuscles: ["Upper Traps"],
    equipment: ["DUMBBELLS"],
    difficulty: "BEGINNER",
    movementType: "ISOLATION",
    instructions: [
      "Stand holding light dumbbells at your sides.",
      "Raise arms out to the sides to shoulder height.",
      "Lower with control.",
    ],
    safetyNotes: "Avoid using momentum; keep the movement controlled.",
  },
  {
    code: "front-raises",
    name: "Front Raise",
    description: "Isolation exercise for the front deltoids.",
    muscleGroup: "Shoulders",
    secondaryMuscles: ["Side Deltoids"],
    equipment: ["DUMBBELLS"],
    difficulty: "BEGINNER",
    movementType: "ISOLATION",
    instructions: [
      "Hold dumbbells in front of your thighs.",
      "Raise them forward to shoulder height.",
      "Lower with control.",
    ],
  },
  {
    code: "rear-delt-fly",
    name: "Rear Delt Fly",
    description: "Isolation exercise for the rear deltoids.",
    muscleGroup: "Shoulders",
    secondaryMuscles: ["Upper Back", "Rhomboids"],
    equipment: ["DUMBBELLS"],
    difficulty: "INTERMEDIATE",
    movementType: "ISOLATION",
    instructions: [
      "Hinge forward over your hips.",
      "Raise dumbbells out to the sides.",
      "Squeeze the rear delts at the top.",
    ],
  },
  {
    code: "pike-push-ups",
    name: "Pike Push Ups",
    description: "A bodyweight shoulder press variation.",
    muscleGroup: "Shoulders",
    secondaryMuscles: ["Triceps", "Chest"],
    equipment: ["NONE"],
    difficulty: "INTERMEDIATE",
    movementType: "BODYWEIGHT",
    instructions: [
      "Form an inverted V with hips high.",
      "Lower your head toward the floor.",
      "Press back up.",
    ],
  },
  // ===== BICEPS =====
  {
    code: "dumbbell-curl",
    name: "Dumbbell Curl",
    description: "The staple biceps isolation exercise.",
    muscleGroup: "Biceps",
    secondaryMuscles: ["Forearms"],
    equipment: ["DUMBBELLS"],
    difficulty: "BEGINNER",
    movementType: "ISOLATION",
    instructions: [
      "Stand holding dumbbells at your sides.",
      "Curl them toward your shoulders.",
      "Lower with control.",
    ],
    safetyNotes: "Keep elbows pinned to your sides.",
  },
  {
    code: "hammer-curl",
    name: "Hammer Curl",
    description: "A neutral-grip curl that also hits the brachialis.",
    muscleGroup: "Biceps",
    secondaryMuscles: ["Brachialis", "Forearms"],
    equipment: ["DUMBBELLS"],
    difficulty: "BEGINNER",
    movementType: "ISOLATION",
    instructions: [
      "Hold dumbbells with palms facing inward.",
      "Curl toward your shoulders.",
      "Lower with control.",
    ],
  },
  {
    code: "band-biceps-curl",
    name: "Resistance Band Curl",
    description: "A band-based biceps curl.",
    muscleGroup: "Biceps",
    secondaryMuscles: ["Forearms"],
    equipment: ["RESISTANCE_BANDS"],
    difficulty: "BEGINNER",
    movementType: "ISOLATION",
    instructions: [
      "Stand on the band and hold the handles.",
      "Curl against the band tension.",
      "Lower with control.",
    ],
  },
  // ===== TRICEPS =====
  {
    code: "triceps-extension",
    name: "Dumbbell Triceps Extension",
    description: "Overhead extension for the triceps.",
    muscleGroup: "Triceps",
    secondaryMuscles: ["Shoulders"],
    equipment: ["DUMBBELLS"],
    difficulty: "BEGINNER",
    movementType: "ISOLATION",
    instructions: [
      "Hold a dumbbell overhead with both hands.",
      "Lower it behind your head.",
      "Extend back to the start.",
    ],
  },
  {
    code: "diamond-push-ups",
    name: "Diamond Push Ups",
    description: "A bodyweight triceps push-up.",
    muscleGroup: "Triceps",
    secondaryMuscles: ["Chest", "Front Deltoids", "Core"],
    equipment: ["NONE"],
    difficulty: "INTERMEDIATE",
    movementType: "BODYWEIGHT",
    instructions: [
      "Place hands close together under your chest.",
      "Lower until chest nears your hands.",
      "Press back up.",
    ],
  },
  {
    code: "triceps-dips",
    name: "Bench Triceps Dips",
    description: "Dips on a bench for the triceps.",
    muscleGroup: "Triceps",
    secondaryMuscles: ["Shoulders", "Chest"],
    equipment: ["BENCH"],
    difficulty: "BEGINNER",
    movementType: "BODYWEIGHT",
    instructions: [
      "Sit on a bench edge with hands beside hips.",
      "Slide off and lower your body.",
      "Push back up to full arm extension.",
    ],
  },
  {
    code: "overhead-band-triceps",
    name: "Overhead Band Triceps Extension",
    description: "A band-based triceps extension.",
    muscleGroup: "Triceps",
    secondaryMuscles: ["Shoulders"],
    equipment: ["RESISTANCE_BANDS"],
    difficulty: "BEGINNER",
    movementType: "ISOLATION",
    instructions: [
      "Anchor the band overhead.",
      "Pull your hands down and outward against tension.",
      "Return with control.",
    ],
  },
  // ===== LEGS =====
  {
    code: "bodyweight-squats",
    name: "Bodyweight Squat",
    description: "A fundamental lower body movement.",
    muscleGroup: "Legs",
    secondaryMuscles: ["Glutes", "Core"],
    equipment: ["NONE"],
    difficulty: "BEGINNER",
    movementType: "COMPOUND",
    instructions: [
      "Stand with feet shoulder-width apart.",
      "Sit your hips back and down to parallel.",
      "Drive back up through your heels.",
    ],
  },
  {
    code: "dumbbell-squat",
    name: "Dumbbell Goblet Squat",
    description: "A loaded squat holding a dumbbell at the chest.",
    muscleGroup: "Legs",
    secondaryMuscles: ["Glutes", "Core"],
    equipment: ["DUMBBELLS"],
    difficulty: "BEGINNER",
    movementType: "COMPOUND",
    instructions: [
      "Hold a dumbbell vertically at your chest.",
      "Squat down keeping the chest tall.",
      "Drive back up.",
    ],
  },
  {
    code: "walking-lunges",
    name: "Walking Lunges",
    description: "Forward lunges for quad and glute strength.",
    muscleGroup: "Legs",
    secondaryMuscles: ["Glutes", "Core"],
    equipment: ["NONE"],
    difficulty: "BEGINNER",
    movementType: "COMPOUND",
    instructions: [
      "Step forward into a lunge.",
      "Lower until both knees are near 90 degrees.",
      "Push off and step forward with the other leg.",
    ],
  },
  {
    code: "leg-raises",
    name: "Dumbbell Romanian Deadlift",
    description: "A hip-hinge movement for the hamstrings.",
    muscleGroup: "Legs",
    secondaryMuscles: ["Glutes", "Lower Back"],
    equipment: ["DUMBBELLS"],
    difficulty: "INTERMEDIATE",
    movementType: "COMPOUND",
    instructions: [
      "Hold dumbbells in front of your thighs.",
      "Hinge at the hips, keeping a soft knee bend.",
      "Lower until you feel a hamstring stretch, then stand.",
    ],
    safetyNotes: "Keep the back flat; do not round the spine.",
  },
  {
    code: "wall-sit",
    name: "Wall Sit",
    description: "An isometric leg strength exercise.",
    muscleGroup: "Legs",
    secondaryMuscles: ["Glutes", "Core"],
    equipment: ["NONE"],
    difficulty: "BEGINNER",
    movementType: "BODYWEIGHT",
    instructions: [
      "Press your back against a wall.",
      "Slide down into a seated position.",
      "Hold the position.",
    ],
  },
  // ===== GLUTES =====
  {
    code: "glute-bridges",
    name: "Glute Bridge",
    description: "A fundamental glute activation exercise.",
    muscleGroup: "Glutes",
    secondaryMuscles: ["Hamstrings", "Core"],
    equipment: ["NONE"],
    difficulty: "BEGINNER",
    movementType: "BODYWEIGHT",
    instructions: [
      "Lie on your back with knees bent.",
      "Drive through heels to lift your hips.",
      "Squeeze glutes at the top, then lower.",
    ],
  },
  {
    code: "hip-thrusts",
    name: "Dumbbell Hip Thrust",
    description: "A loaded glute movement.",
    muscleGroup: "Glutes",
    secondaryMuscles: ["Hamstrings", "Core"],
    equipment: ["DUMBBELLS", "BENCH"],
    difficulty: "INTERMEDIATE",
    movementType: "COMPOUND",
    instructions: [
      "Rest your upper back on a bench with a dumbbell on your hips.",
      "Drive hips up to a full glute contraction.",
      "Lower with control.",
    ],
  },
  {
    code: "fire-hydrants",
    name: "Fire Hydrant",
    description: "An isolation exercise for the glute medius.",
    muscleGroup: "Glutes",
    secondaryMuscles: ["Core"],
    equipment: ["NONE"],
    difficulty: "BEGINNER",
    movementType: "ISOLATION",
    instructions: [
      "Start on all fours.",
      "Lift one knee out to the side keeping the hip level.",
      "Lower with control.",
    ],
  },
  // ===== CORE =====
  {
    code: "plank",
    name: "Plank",
    description: "A foundational core stability exercise.",
    muscleGroup: "Core",
    secondaryMuscles: ["Shoulders", "Glutes"],
    equipment: ["NONE"],
    difficulty: "BEGINNER",
    movementType: "CORE",
    instructions: [
      "Support your body on forearms and toes.",
      "Keep the body in a straight line.",
      "Hold without sagging the hips.",
    ],
  },
  {
    code: "russian-twists",
    name: "Russian Twist",
    description: "An oblique-focused rotational movement.",
    muscleGroup: "Core",
    secondaryMuscles: ["Hip Flexors"],
    equipment: ["NONE", "DUMBBELLS"],
    difficulty: "BEGINNER",
    movementType: "CORE",
    instructions: [
      "Sit with knees bent and lean back slightly.",
      "Rotate your torso side to side.",
      "Keep the chest tall.",
    ],
  },
  {
    code: "leg-raises-core",
    name: "Leg Raises",
    description: "A lower abdominal exercise.",
    muscleGroup: "Core",
    secondaryMuscles: ["Hip Flexors"],
    equipment: ["NONE"],
    difficulty: "INTERMEDIATE",
    movementType: "CORE",
    instructions: [
      "Lie on your back with legs straight.",
      "Raise legs to vertical.",
      "Lower slowly without arching the lower back.",
    ],
  },
  {
    code: "mountain-climbers",
    name: "Mountain Climbers",
    description: "A dynamic core and cardio move.",
    muscleGroup: "Core",
    secondaryMuscles: ["Shoulders", "Hip Flexors", "Cardio"],
    equipment: ["NONE"],
    difficulty: "BEGINNER",
    movementType: "CORE",
    instructions: [
      "Start in a plank position.",
      "Drive knees toward your chest alternately.",
      "Keep hips level and pace steady.",
    ],
  },
  {
    code: "dead-bug",
    name: "Dead Bug",
    description: "A low-back friendly core exercise.",
    muscleGroup: "Core",
    secondaryMuscles: ["Hip Flexors"],
    equipment: ["NONE"],
    difficulty: "BEGINNER",
    movementType: "CORE",
    instructions: [
      "Lie on your back with arms up and knees bent.",
      "Lower one arm and opposite leg toward the floor.",
      "Return and switch sides.",
    ],
  },
  // ===== CARDIO =====
  {
    code: "jumping-jacks",
    name: "Jumping Jacks",
    description: "A full-body cardio movement.",
    muscleGroup: "Cardio",
    secondaryMuscles: ["Legs", "Shoulders"],
    equipment: ["NONE"],
    difficulty: "BEGINNER",
    movementType: "CARDIO",
    instructions: [
      "Jump while spreading arms and legs.",
      "Return to the start position and repeat.",
      "Keep a steady rhythm.",
    ],
  },
  {
    code: "high-knees",
    name: "High Knees",
    description: "A dynamic cardio sprint drill.",
    muscleGroup: "Cardio",
    secondaryMuscles: ["Legs", "Core"],
    equipment: ["NONE"],
    difficulty: "BEGINNER",
    movementType: "CARDIO",
    instructions: [
      "Run in place driving knees to hip height.",
      "Swing arms in rhythm.",
      "Keep a quick pace.",
    ],
  },
  {
    code: "burpees",
    name: "Burpees",
    description: "A full-body high-intensity movement.",
    muscleGroup: "Cardio",
    secondaryMuscles: ["Chest", "Legs", "Core", "Shoulders"],
    equipment: ["NONE"],
    difficulty: "ADVANCED",
    movementType: "CARDIO",
    instructions: [
      "Squat down and place hands on the floor.",
      "Kick back into a plank.",
      "Return to the squat and jump up.",
    ],
    safetyNotes: "Modify as needed; land softly.",
  },
  {
    code: "jump-rope",
    name: "Jump Rope",
    description: "A classic cardiovascular conditioning drill.",
    muscleGroup: "Cardio",
    secondaryMuscles: ["Legs", "Calves", "Shoulders"],
    equipment: ["NONE"],
    difficulty: "BEGINNER",
    movementType: "CARDIO",
    instructions: [
      "Hold the rope handles at hip height.",
      "Jump with a soft bounce as the rope passes.",
      "Keep elbows in and wrists active.",
    ],
  },
  // ===== MOBILITY =====
  {
    code: "cat-cow",
    name: "Cat Cow Stretch",
    description: "Spinal mobility and warm-up movement.",
    muscleGroup: "Mobility",
    secondaryMuscles: ["Core", "Back"],
    equipment: ["NONE"],
    difficulty: "BEGINNER",
    movementType: "MOBILITY",
    instructions: [
      "Start on all fours.",
      "Arch the back and lift the head (cow).",
      "Round the back and tuck the chin (cat).",
    ],
  },
  {
    code: "worlds-greatest-stretch",
    name: "World's Greatest Stretch",
    description: "A full-body dynamic mobility flow.",
    muscleGroup: "Mobility",
    secondaryMuscles: ["Hips", "Chest", "Back"],
    equipment: ["NONE"],
    difficulty: "BEGINNER",
    movementType: "MOBILITY",
    instructions: [
      "Step into a deep lunge.",
      "Rotate your torso toward the forward leg.",
      "Sweep the arm up and repeat on the other side.",
    ],
  },
  {
    code: "hip-flexor-stretch",
    name: "Kneeling Hip Flexor Stretch",
    description: "Opens the hip flexors.",
    muscleGroup: "Mobility",
    secondaryMuscles: ["Hips", "Quads"],
    equipment: ["NONE"],
    difficulty: "BEGINNER",
    movementType: "MOBILITY",
    instructions: [
      "Kneel on one knee.",
      "Square the hips and squeeze the glute.",
      "Lean slightly forward for a stretch.",
    ],
  },
  {
    code: "shoulder-circles",
    name: "Shoulder Circles",
    description: "Warm-up mobility for the shoulder joint.",
    muscleGroup: "Mobility",
    secondaryMuscles: ["Shoulders"],
    equipment: ["NONE"],
    difficulty: "BEGINNER",
    movementType: "MOBILITY",
    instructions: [
      "Extend arms out to the sides.",
      "Make controlled forward circles.",
      "Reverse the direction.",
    ],
  },
];

export const achievementDefinitions = [
  {
    key: "first_workout",
    name: "First Workout",
    description: "Complete your very first workout.",
    icon: "Zap",
    xpReward: 50,
  },
  {
    key: "streak_3",
    name: "3 Day Streak",
    description: "Complete workouts on 3 consecutive days.",
    icon: "Flame",
    xpReward: 100,
  },
  {
    key: "streak_7",
    name: "7 Day Streak",
    description: "Complete workouts on 7 consecutive days.",
    icon: "Flame",
    xpReward: 250,
  },
  {
    key: "workouts_10",
    name: "10 Workouts",
    description: "Complete 10 workouts in total.",
    icon: "Trophy",
    xpReward: 150,
  },
  {
    key: "workouts_25",
    name: "25 Workouts",
    description: "Complete 25 workouts in total.",
    icon: "Trophy",
    xpReward: 400,
  },
  {
    key: "workouts_50",
    name: "50 Workouts",
    description: "Complete 50 workouts in total.",
    icon: "Medal",
    xpReward: 1000,
  },
  {
    key: "first_pr",
    name: "Personal Record",
    description: "Set your first personal record on an exercise.",
    icon: "TrendingUp",
    xpReward: 100,
  },
  {
    key: "weekly_goal",
    name: "Weekly Goal",
    description: "Hit your weekly workout goal.",
    icon: "CalendarCheck",
    xpReward: 200,
  },
];

